tasks:
  - name: Setup and Build
    before: 
      # Download and Install 18.14.0
      VERSION="16.20.2" \
      && source $HOME/.nvm/nvm.sh && nvm install $VERSION \
      && nvm use $VERSION && nvm alias default $VERSION
